### ISSUE TITLE
plot_cnvr_panorama issue in HandyCNV

### ISSUE THREAD

**Issue by oshintogla** [JH-Zhou/HandyCNV#17]
Thank you for providing this user friendly package. I am facing the problem in few commands as I was generating the different maps for my beadchip data. I have generated CNVs by PennCNV software and then did the whole descriptive analysis based on CNVRs (by HandyCNV) in Handycnv only. Unfortunately, while using the plot_cnvr_panorama command , I am facing different kinds of problems. I am getting the following message right now in R: Error in nrow(cnv_chr_zoom.byId) : object 'cnv_chr_zoom.byId' not found. I am sure about the files I am using, what could be the reason? Also, Troubleshooting have created many doubts in my mind right now. While detecting the CNVs, I generated the intensity files in different kind of format than what we need to use in this package, however there is no discrepancies of any values, does it make any difference? Also, the quality check made is the same for map, bed and intensity files used here in the package, but it differs from the intensity file I used for PennCNV. 
![Screenshot from 2022-04-26 20-44-51](https://user-images.githubusercontent.com/76421591/165334083-e45dcad3-2add-4138-8aba-2e29c6bdbcac.png)
![Screenshot from 2022-04-26 20-45-20](https://user-images.githubusercontent.com/76421591/165334120-c42c6a53-9aeb-40de-9f3a-e89b440f3401.png)
Ist SS is the file I am using for HandyCNV and 2nd SS is what I used for PennCNV.

**Comment by JH-Zhou** [comment]
Thank you for reporting this issue. The intensity file you presented here are the correct formats and 1st file should be work with this function. The error occured since the absence of the object `cnv_chr_zoom.byId`, which is a temporary dataframe while preparing the plot data, but I'm not sure what caused this problem with current information. How many input files did you used? Are the three files,  `cnvr` list, `intensity` and `map` ? If all the files you provide in correct format, the other possible impacts will be the version of R and the oprateing system.

**Comment by oshintogla** [comment]
The command I used is as - plot_cnvr_panorama(cnvr = "cnvr/cnvr.txt", cnv_annotation = "call_gene1/cnv_annotation.txt",intensity = "KF44.txt", map = "KF3auto.map",prefix_bed = "KF2auto", ld_heat = TRUE, sample_size = 44, common_cnv_threshold = 0.01).

The SS of respective files used  are as attached: 
![cnvrtxt](https://user-images.githubusercontent.com/76421591/165684372-b2b0ab85-f0f5-44dc-90be-c9c4f4d07c7a.png)
![KF3automap](https://user-images.githubusercontent.com/76421591/165684757-248ccf6b-b504-4974-8cc5-5be449315a08.png)
![cnvr_annotationtxt](https://user-images.githubusercontent.com/76421591/165684882-2cbf6b09-498e-4a9a-aec3-907d85a65893.png)

Which version of R needs to be installed for this? 

Also, the quality check made is the same for map, bed and intensity files used here in the package, but it differs from the intensity file I used for PennCNV. Does this make any difference?

**Comment by JH-Zhou** [comment]
I am using the 3.5.2 of R in Win10 system. 
The intensity file you used in PennCNV might has been corrected by the GC contents, which may account for the difference between the two files, it will have a little impact on the CNV detection.

**Comment by oshintogla** [comment]
Dear Sir, I have tried every possible way out from my side and I am still getting these errors. I dont  know where the problem lies. Kindly help.
1. Error in seq.default(1, nrow(id_coord), 1) : wrong sign in 'by' argument
Error in seq.default(start_position, end_position, by = 250000) : 
  'from' must be a finite number

2. Error in LD(x, c(which(x@snps$id == sub_inten$`SNP Name`[1]), which(x@snps$id ==  : 
  lim must be a vector of length 2
